CREATE TABLE `product_info` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `platform` varchar(100) NOT NULL COMMENT '商品所属平台',
  `city` varchar(255) NOT NULL COMMENT '商品上架平台所属城市',
  `platform_product_id` varchar(255) NOT NULL COMMENT '平台产品id',
  `product_image` text COMMENT '产品图片',
  `title` text COMMENT '产品标题',
  `desc` text COMMENT '产品描述',
  `brand` varchar(255) DEFAULT NULL COMMENT '产品生产厂家',
  `color` varchar(255) DEFAULT NULL COMMENT '产品颜色',
  `size` varchar(255) DEFAULT NULL COMMENT '产品尺寸',
  `price` decimal(10,2) DEFAULT NULL COMMENT '产品价格',
  `currency` varchar(100) DEFAULT NULL COMMENT '货币种类',
  `estimate_num` int(11) DEFAULT NULL COMMENT '产品评价数',
  `multi` tinyint(1) DEFAULT NULL COMMENT '是否多变体',
  `remark` varchar(255) DEFAULT NULL COMMENT '备注',
  `create_time` datetime(6) DEFAULT NULL COMMENT '创建时间',
  `create_by` varchar(50) DEFAULT NULL COMMENT '创建者',
  `update_time` datetime(6) DEFAULT NULL COMMENT '更新时间',
  `update_by` varchar(50) DEFAULT NULL COMMENT '更新者',
  `del_flag` tinyint(1) NOT NULL COMMENT '是否已删除',
  PRIMARY KEY (`id`),
  KEY `platform` (`platform`,`city`),
  KEY `platform_product_id` (`platform_product_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='产品信息表集合';